# CS Materials id (gamemtl.xr):
gamemtlCS = {
0   :  'default',
1   :  'creatures\\human',
2   :  'materials\\wood',
3   :  'materials\\concrete',
4   :  'materials\\asphalt',
5   :  'materials\\metal',
6   :  'materials\\glass',
7   :  'materials\\earth',
8   :  'materials\\gravel',
10  :  'materials\\dirt',
11  :  'materials\\water',
12  :  'materials\\flooring_tile',
13  :  'materials\\metal_plate',
15  :  'materials\\grass',
16  :  'materials\\sand',
18  :  'materials\\bricks',
19  :  'materials\\wooden_board',
22  :  'objects\\large_weapon',
24  :  'objects\\tin_can',
34  :  'materials\\metal_pipe',
37  :  'materials\\bush',
38  :  'objects\\bullet',
39  :  'materials\\tree_trunk',
48  :  'materials\\setka_rabica',
49  :  'materials\\shifer',
53  :  'materials\\stucco',
58  :  'creatures\\large',
60  :  'materials\\tin',
61  :  'objects\\car_cabine',
63  :  'creatures\\medium',
64  :  'creatures\\small',
65  :  'objects\\clothes',
66  :  'objects\\small_box',
67  :  'objects\\small_weapon',
69  :  'objects\\dead_body',
70  :  'objects\\bottle',
71  :  'objects\\barrel',
72  :  'objects\\metal_box',
73  :  'objects\\small_metal_trash',
74  :  'objects\\large_metal_trash',
75  :  'objects\\car_wheel',
76  :  'objects\\large_furniture',
77  :  'objects\\fuel_can',
78  :  'objects\\concrete_box',
79  :  'objects\\knife',
80  :  'materials\\fake',
81  :  'materials\\cloth',
82  :  'materials\\fake_ladders',
83  :  'default_object',
84  :  'objects\\monster_body',
85  :  'creatures\\hoof',
86  :  'objects\\glass',
88  :  'materials\\death',
90  :  'creatures\\actor',
91  :  'creatures\\human_head',
92  :  'creatures\\phantom',
93  :  'materials\\earth_death',
94  :  'materials\\earth_slide',
95  :  'materials\\bush_sux',
96  :  'materials\\water_radiation'
}
ids = list(gamemtlCS.keys())
ids.sort()
print('CS Materials:\n')
for id in ids:
    print('{: <3} {}'.format(id, gamemtlCS[id]))
input()